<?php
// This file is part of Moodle - http://moodle.org/

defined('MOODLE_INTERNAL') || die();

$string['pluginname'] = 'UCKK reports';

$string['settings'] = 'UCKK report settings';
$string['settings:allowjsonexport'] = 'Allow JSON export';
$string['settings:allowjsonexport_desc'] = 'Allow authorized users to export report rows as JSON for internal audit.';
$string['settings:showemptyreports'] = 'Show empty report cards';
$string['settings:showemptyreports_desc'] = 'Display report cards even when the source table has no rows yet.';
$string['settings:defaultlimit'] = 'Default row limit';
$string['settings:defaultlimit_desc'] = 'Maximum number of rows shown or exported by default.';

$string['dashboard'] = 'Institutional report dashboard';
$string['reports'] = 'Reports';
$string['report'] = 'Report';
$string['filters'] = 'Filters';
$string['applyfilters'] = 'Apply filters';
$string['clearfilters'] = 'Clear filters';
$string['exportcsv'] = 'Export CSV';
$string['exportjson'] = 'Export JSON';
$string['exporthtml'] = 'HTML view';
$string['norows'] = 'No records match the selected filters.';
$string['totalrows'] = '{$a} matching rows';
$string['viewreport'] = 'View report';
$string['activefilters'] = 'Active filters';
$string['all'] = 'All';
$string['from'] = 'From timestamp';
$string['to'] = 'To timestamp';
$string['limit'] = 'Limit';
$string['status'] = 'Status';
$string['visibility'] = 'Visibility';
$string['user'] = 'User ID';
$string['cohort'] = 'Cohort ID';
$string['program'] = 'Program ID';
$string['course'] = 'Course ID';
$string['category'] = 'Category ID';
$string['competency'] = 'Competency ID';
$string['badge'] = 'Badge ID';
$string['challengetype'] = 'Challenge type';
$string['assemblytype'] = 'Assembly type';
$string['integritytype'] = 'Integrity type';

$string['privacy:metadata'] = 'The UCKK report plugin stores no primary personal data. It displays derived data from other UCKK components.';

$string['eventreportexported'] = 'UCKK report exported';

$string['notavailable'] = 'Not available';
$string['notinstalled'] = 'The required source table is not installed yet.';
$string['unknownreport'] = 'Unknown report.';
$string['unknown'] = 'Unknown';
$string['generatedat'] = 'Generated at';
$string['generatedby'] = 'Generated by';
$string['source'] = 'Source';
$string['summary'] = 'Summary';
$string['count'] = 'Count';
$string['records'] = 'Records';
$string['actions'] = 'Actions';

$string['report:player_progress'] = 'Joueur progress';
$string['report:cohort_progress'] = 'Cohort progress';
$string['report:program_progress'] = 'Program progress';
$string['report:competency_matrix'] = 'Competency matrix';
$string['report:badge_awards'] = 'Badge awards';
$string['report:challenge_status'] = 'Challenge status';
$string['report:assembly_decisions'] = 'Assembly decisions';
$string['report:archive_production'] = 'Archive production';
$string['report:integrity_cases'] = 'Integrity cases';

$string['reportdesc:player_progress'] = 'Pathway, portfolio, profile visibility, and integrity indicators for Joueurs.';
$string['reportdesc:cohort_progress'] = 'Cohort membership counts and course progress context.';
$string['reportdesc:program_progress'] = 'UCKK programs, categories, pathways, and status.';
$string['reportdesc:competency_matrix'] = 'Competency evidence and ratings across the UCKK framework.';
$string['reportdesc:badge_awards'] = 'Badge issue counts and award dates.';
$string['reportdesc:challenge_status'] = 'Défi status, submissions, validation, and integrity review indicators.';
$string['reportdesc:assembly_decisions'] = 'Assemblée motions, decisions, contestability, and archive links.';
$string['reportdesc:archive_production'] = 'Archive items by type, validation state, visibility, and provenance source.';
$string['reportdesc:integrity_cases'] = 'Inquisiteur cases by type, severity, status, assignment, and archive summary.';

$string['column:id'] = 'ID';
$string['column:name'] = 'Name';
$string['column:user'] = 'User';
$string['column:email'] = 'Email';
$string['column:course'] = 'Course';
$string['column:category'] = 'Category';
$string['column:cohort'] = 'Cohort';
$string['column:program'] = 'Program';
$string['column:programtype'] = 'Program type';
$string['column:pathways'] = 'Pathways';
$string['column:portfolio'] = 'Portfolio archive';
$string['column:integrity'] = 'Integrity flags';
$string['column:visibility'] = 'Visibility';
$string['column:status'] = 'Status';
$string['column:total'] = 'Total';
$string['column:members'] = 'Members';
$string['column:players'] = 'Players';
$string['column:courses'] = 'Courses';
$string['column:competency'] = 'Competency';
$string['column:rating'] = 'Rating';
$string['column:ratings'] = 'Ratings';
$string['column:badge'] = 'Badge';
$string['column:issued'] = 'Issued';
$string['column:lastissued'] = 'Last issued';
$string['column:challenge'] = 'Challenge';
$string['column:challengetype'] = 'Challenge type';
$string['column:submissions'] = 'Submissions';
$string['column:validated'] = 'Validated';
$string['column:contested'] = 'Contested';
$string['column:assembly'] = 'Assembly';
$string['column:assemblytype'] = 'Assembly type';
$string['column:motions'] = 'Motions';
$string['column:decisions'] = 'Decisions';
$string['column:archiveitem'] = 'Archive item';
$string['column:itemtype'] = 'Item type';
$string['column:sourcecomponent'] = 'Source component';
$string['column:validationstate'] = 'Validation state';
$string['column:casetype'] = 'Case type';
$string['column:severity'] = 'Severity';
$string['column:assignedto'] = 'Assigned to';
$string['column:openedby'] = 'Opened by';
$string['column:created'] = 'Created';
$string['column:modified'] = 'Modified';
$string['column:archive'] = 'Archive';

$string['report/uckk:view'] = 'View UCKK reports';
$string['report/uckk:viewall'] = 'View all UCKK report data';
$string['report/uckk:export'] = 'Export UCKK reports';